spring.application.name=Employee_Management_Backend
spring.datasource.url=jdbc:mysql://localhost:3306/sitdemo
spring.datasource.name=sitdemo
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port = 8081